package com.aura.emergencyactivation.domain.model;

import com.aura.shared.domain.exception.BusinessRuleViolationException;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Aggregate Root for the Emergency Activation bounded context.
 *
 * <p>Manages the incident state machine:
 * ACTIVATED → RECORDING → UPLOADED → PROCESSING → DRAFT_READY → APPROVED → EXPORTED → CLOSED (plus CANCELLED).
 *
 * <p>Persistence-ignorant: no Spring or MongoDB annotations here.
 * All state mutations enforce domain invariants and log transitions into status history.
 */
public class Incident {

    private final IncidentId id;
    private final String userId;
    private IncidentStatus status;
    private final GpsLocation gpsLocation;
    private final Instant activatedAt;
    private final List<StatusTransition> statusHistory;
    private Instant closedAt;

    private Incident(
            IncidentId id,
            String userId,
            IncidentStatus status,
            GpsLocation gpsLocation,
            Instant activatedAt,
            List<StatusTransition> statusHistory,
            Instant closedAt
    ) {
        if (userId == null || userId.isBlank()) {
            throw new BusinessRuleViolationException("User ID must not be blank");
        }
        this.id = Objects.requireNonNull(id, "IncidentId must not be null");
        this.userId = userId.trim();
        this.status = Objects.requireNonNull(status, "IncidentStatus must not be null");
        this.gpsLocation = Objects.requireNonNull(gpsLocation, "GpsLocation must not be null");
        this.activatedAt = Objects.requireNonNull(activatedAt, "activatedAt must not be null");
        this.statusHistory = new ArrayList<>(Objects.requireNonNull(statusHistory, "statusHistory must not be null"));
        this.closedAt = closedAt;
    }

    /**
     * Factory method to activate a new Incident.
     */
    public static Incident activate(String userId, GpsLocation location) {
        IncidentId newId = IncidentId.generate();
        Instant now = Instant.now();
        List<StatusTransition> history = new ArrayList<>();
        history.add(StatusTransition.initial(IncidentStatus.ACTIVATED));

        return new Incident(
                newId,
                userId,
                IncidentStatus.ACTIVATED,
                location,
                now,
                history,
                null
        );
    }

    /**
     * Reconstitutes an Incident from persistence layer.
     */
    public static Incident reconstitute(
            IncidentId id,
            String userId,
            IncidentStatus status,
            GpsLocation gpsLocation,
            Instant activatedAt,
            List<StatusTransition> statusHistory,
            Instant closedAt
    ) {
        return new Incident(id, userId, status, gpsLocation, activatedAt, statusHistory, closedAt);
    }

    /**
     * Transitions incident state to RECORDING.
     */
    public void markRecording() {
        transitionTo(IncidentStatus.RECORDING, "Mobile device started covert recording");
    }

    /**
     * Transitions incident state to UPLOADED.
     */
    public void markUploaded() {
        transitionTo(IncidentStatus.UPLOADED, "All evidence streams uploaded");
    }

    /**
     * Transitions incident state to PROCESSING.
     */
    public void markProcessing() {
        transitionTo(IncidentStatus.PROCESSING, "AI analysis pipeline started");
    }

    /**
     * Transitions incident state to DRAFT_READY.
     */
    public void markDraftReady() {
        transitionTo(IncidentStatus.DRAFT_READY, "Incident report draft generated by AI");
    }

    /**
     * Approves the incident report.
     */
    public void approve() {
        transitionTo(IncidentStatus.APPROVED, "User approved incident report");
    }

    /**
     * Marks the incident report as EXPORTED.
     */
    public void export() {
        transitionTo(IncidentStatus.EXPORTED, "Incident report exported for legal entity");
    }

    /**
     * Closes the incident.
     */
    public void close() {
        transitionTo(IncidentStatus.CLOSED, "Incident closed");
        this.closedAt = Instant.now();
    }

    /**
     * Cancels the incident (false alarm).
     */
    public void cancel(String reason) {
        String cancelReason = (reason != null && !reason.isBlank()) ? reason : "False alarm cancelled by user";
        transitionTo(IncidentStatus.CANCELLED, cancelReason);
        this.closedAt = Instant.now();
    }

    /**
     * Enforces transition validation and adds to status history.
     */
    public void transitionTo(IncidentStatus targetStatus, String reason) {
        if (!this.status.canTransitionTo(targetStatus)) {
            throw new InvalidIncidentStateTransitionException(this.status, targetStatus);
        }
        StatusTransition transition = StatusTransition.of(this.status, targetStatus, reason);
        this.statusHistory.add(transition);
        this.status = targetStatus;
    }

    // Getters

    public IncidentId getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public IncidentStatus getStatus() {
        return status;
    }

    public GpsLocation getGpsLocation() {
        return gpsLocation;
    }

    public Instant getActivatedAt() {
        return activatedAt;
    }

    public List<StatusTransition> getStatusHistory() {
        return Collections.unmodifiableList(statusHistory);
    }

    public Instant getClosedAt() {
        return closedAt;
    }
}
